CREATE DATABASE IF NOT EXISTS xillow;

USE xillow;

DROP TABLE IF EXISTS photo;
DROP TABLE IF EXISTS property;

CREATE TABLE property (
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  bed_count INT NOT NULL,
  bath_count INT NOT NULL,
  sq_ft INT NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE photo (
  id INT AUTO_INCREMENT NOT NULL,
  property_id INT NOT NULL,
  url VARCHAR(2048) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (property_id) REFERENCES property(id)
);